apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: controller
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: controller
    spec:
      containers:
      - image: msreetej/teju:1.0
        name: teju
        resources: {}
status: {}
